#!/usr/bin/perl

# This script installs Robby Russell's 'Oh-My-Zsh'
# https://github.com/robbyrussell/oh-my-zsh/
# It requires zsh present, so remember to put that in you brewkegs.yml
# The (primitive) way to test if an install is needed - or if it's already present
# is to test if the  ~/.oh-my-zsh/ folder exists

print "I'm running";
`echo "I ran" > ~/doesntexist`;
